### ISSUE TITLE
2 factor authentication error.

### ISSUE THREAD

**Issue by mjfusa** [Azure-Samples/active-directory-dotnet-native-uwp-v2#1]
I'm getting an error '
```
An error occurred 

No valid client certificate found in the request. No valid certificates found in the user's certificate store. Please try again choosing a different authentication method. 
```
when attempting to login with an account that has 2 factor authentication enabled.
Steps to reproduce:
1) Build and run this sample. (active-directory-dotnet-native-uwp-v2)
2) Click 'Call Microsoft Graph API'
3) Login with account that has 2 factor authentication enabled (an @Microsoft.com account for example).
4) Click 'Sign in with PIN or smartcard'
5) A message about a pop up is briefly displayed. Followed by the error mentioned above.

How can I login using my 2 factor PIN or certificate?

**Comment by jmprieur** [comment]
This is a limitation of WAB on the UWP platform. 
the workaround is to select "signin with alternate methods" (other than the PIN). The phone authentication works.
