### ISSUE TITLE
Windows Hello PIN/Smartcard issue resolved?

### ISSUE THREAD

**Issue by mark-szabo** [Azure-Samples/active-directory-dotnet-native-uwp-v2#12]
Can somebody please check if the issue mentioned [in the README below Known limitation](https://github.com/Azure-Samples/active-directory-dotnet-native-uwp-v2/blob/master/README.md#known-limitation-on-windows-10-you-cannot-sign-in-with-your-windows-hello-pin) is resolved by enabling `Shared User Certificates` on `package.appxmanifest`'s Capabilities tab?

![image](https://user-images.githubusercontent.com/3098994/46585209-350c1e00-ca6e-11e8-9db9-55edff6a7cb8.png)

More info: https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-windows-uwp#enable-integrated-authentication-on-federated-domains-optional

**Comment by mark-szabo** [comment]
Ok, this seems to be more like a workaround than a solution...

![image](https://user-images.githubusercontent.com/3098994/46585547-946c2d00-ca72-11e8-9085-599eeec30e3f.png)

**Comment by bgavrilMS** [comment]
Yes, please use WAM. I'll make an effort to update this sample, but see https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-desktop-acquire-token-wam
