### ISSUE TITLE
why MSAL freeze on UWP app on AcquireTokenInteractive?

### ISSUE THREAD

**Issue by xanscale** [Azure-Samples/active-directory-dotnet-native-uwp-v2#46]
often after entering the password and clicking on proceed I am blocked without receiving errors. sometimes it works correctly if i repeating the operation several times.

https://stackoverflow.com/questions/71103563/why-msal-freeze-on-uwp-app-on-acquiretokeninteractive

**Comment by joseluisct** [comment]
Same problem here. It happens a lot of times, blocking without errors, it seems random. Is there any workaround?

**Comment by bgavrilMS** [comment]
The workaround is to use WAM - https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-desktop-acquire-token-wam

**Comment by bgavrilMS** [comment]
Let's track this on the MSAL repo - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3109
