### ISSUE TITLE
Can't authenticate @live.com user

### ISSUE THREAD

**Issue by a-d-atanasov** [Azure-Samples/active-directory-dotnet-native-uwp-v2#6]
Hi,

I followed the steps, registered a new app and changed the client id in the code. When I login with my work account it works fine and I'm authenticated. But when I try to login with my personal Microsoft account there's an error after I write my email and click Next:

We're unable to complete your request
Microsoft account is experiencing technical problems. Please try again later.

Why is that?

**Comment by jazzzsoftware** [comment]
You need to register the app with Microsoft.

**Comment by kalyankrishna1** [comment]
Please download the latest sample code and try again with the @live account.
